# Generated by Django 5.0.3 on 2024-03-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='bid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
