# Generated by Django 5.0.3 on 2024-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tracker_bid_tracker_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='fname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='lname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
