# Generated by Django 5.0.3 on 2024-03-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_tracker_fname_alter_tracker_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='bid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='uid',
            field=models.IntegerField(blank=True),
        ),
    ]
