# Generated by Django 5.0.3 on 2024-03-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_tracker_bid_alter_tracker_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
